### ISSUE TITLE
Ability to use host ssh keys into container

### ISSUE THREAD

**Issue by isholgueras** [keopx/docker-apache-php#4]
When using drush aliases, (ie: drush @prod status) sometimes you need your ssh credentials.

In Vagrant, I used to execute "ssh -L vagrant@vagrant..." to use my own keys, but I cannot find a good way in Docker.

I figured out to add it on demand (write my keys each time I need it) but there is no /home/me directory created.

Any idea? Is that useful?

**Comment by keopx** [comment]
You can uncomment ssh in docker-lamp docker-compose.yml @isholgueras 

https://github.com/keopx/docker-lamp/blob/master/README.md#ssh

**Comment by keopx** [comment]
I closed this issue.

Reopen if you need more support :-*
