### ISSUE TITLE
Add pngcrush and jpegtran

### ISSUE THREAD

**Issue by jameswilson** [keopx/docker-apache-php#7]
Google is now penalizing sites for not optimizing front-end resources.

We're building all our sites now to include the `imageapi_optimize` module configured with JpegTran and PngCrush to do server-side optimizations on all images served through Drupal image styles system.

For now we're currently using a custom Dockerfile as a wrapper around keopx/apache-php to add the libraries to the server.

https://github.com/BluesparkLabs/apache-php/blob/master/Dockerfile#L6

Was just wondering if there was any possibility you'd accept a pull request that adds these binaries to your image?

Thanks!

**Comment by keopx** [comment]
Thanks for review. I have this packages on producction but not in this repo.

Added libraries:
* libjpeg-turbo-progs
* libjpeg-progs
* pngcrush
* optipng

Commit: 4fe14c9099bbdfa748f8e5964c0122a394a3ea9c

**Comment by keopx** [comment]
@jameswilson all PR are welcome :)

**Comment by jameswilson** [comment]
Had a look, and the commit looks good to me.  Thanks very much!
