### ISSUE TITLE
Error al levantar el contenedor

### ISSUE THREAD

**Issue by oskarcalvo** [keopx/docker-apache-php#8]
al ejecutar:

`docker run keopx/apache-php:7.1`

Me devuelve:

`
/usr/bin/apache2-foreground: line 8: /etc/php/7.2/apache2/conf.d/zzz-docker-php.ini: No such file or directory
`

Por lo que veo el problema puede ser del cambio de hace 9 días en el repo con el cambio.

**Comment by keopx** [comment]
@oskarcalvo corregido, están compilándose las imágenes, pasado un rato hazte un docker-compose pull

* Status: https://hub.docker.com/r/keopx/apache-php/builds
